import Head from 'next/head'
import Navbar from 'components/navbar/navbar'
import Body from 'components/body/body'
import styles from '/styles/Home.module.css'


export default function Home() {
  return (
  <>
  <Head>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Navbar/>  
  <Body/>
  </>
  )
}
